### ISSUE TITLE
Add fast data loader for python

### ISSUE THREAD

**Issue by batson** [czbiohub/tabula-muris-vignettes#1]
For fast loading into python, we will use h5 files in the AnnData format (which are also readable with generic hdf5 readers). Those will contain just the counts matrix (rownames, colnames, entries). We will still store the metadata in version controlled CSVs on github.

**Comment by jamestwebber** [comment]
We should also consider and benchmark the Quilt solution–it's compressed Parquet so it should be similarly fast to download/load.

**Comment by batson** [comment]
Changed name of this. Goal is a fast way into python, I'm not opinionated on how. < 10sec to load the whole dataset is the benchmark to beat. quilt would be awesome too, hdf5 also fine.

**Comment by jamestwebber** [comment]
I emailed support at Quilt. Short version is that while they use Parquet on the backend, they serve up normal (uncompressed) DataFrames to the user, so the standard approach won't work (at least when trying to load everything at once).

We can work around that by basically storing blobs, and using their library as a nice download tool. At that point we need to decide on our own file format, so perhaps AnnData is the way to go after all.

**Comment by batson** [comment]
Done. Used `h5ad` for now.
